version: '3'

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data:/data
            - ./conf/redis.conf:/etc/redis.conf
        networks:
            localnet:
                aliases:
                    - my-redis-server
        command: ["redis-server", "/etc/redis.conf"]

networks:
    localnet: 
