version: '3'

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data:/data
            - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            localnet:
                aliases:
                    - my-redis-server

networks:
    localnet: 
